# Generated by Django 5.0.7 on 2024-07-11 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=50)),
                ('ai_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_comment', models.TextField()),
                ('weekly_comment', models.TextField()),
                ('yearly_comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_probabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
