# Generated by Django 5.0.7 on 2024-07-13 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0003_alter_personalizedprobability_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedprobability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_probabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relative',
            name='role',
            field=models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Child', 'Child'), ('Other', 'Other')], max_length=20),
        ),
    ]
