# Generated by Django 5.0.7 on 2024-07-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0004_alter_personalizedprobability_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbabilitiesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_sign', models.CharField(max_length=20)),
                ('ascendant_sign', models.CharField(max_length=20)),
                ('daily_comment', models.TextField()),
                ('weekly_comment', models.TextField()),
                ('yearly_comment', models.TextField()),
            ],
            options={
                'unique_together': {('sun_sign', 'ascendant_sign')},
            },
        ),
        migrations.AddField(
            model_name='personalizedprobability',
            name='probabilities_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_probabilities', to='natalcharts.probabilitiescomments'),
        ),
    ]
