# Generated by Django 5.0.7 on 2024-07-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0005_probabilitiescomments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProbabilitiesComments',
            new_name='ProbabilitiesComment',
        ),
    ]
