# Generated by Django 5.0.7 on 2024-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0007_rename_probabilitiescomment_probabilitiescomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedprobability',
            name='monthly_comment',
            field=models.TextField(default='Default monthly comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probabilitiescomments',
            name='monthly_comment',
            field=models.TextField(default='Default monthly comment'),
            preserve_default=False,
        ),
    ]
