# Generated by Django 5.0.7 on 2024-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0008_personalizedprobability_monthly_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroFunContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_sign', models.CharField(max_length=20)),
                ('ascendant_sign', models.CharField(max_length=20)),
                ('movie_recommendation', models.TextField()),
                ('song_recommendation', models.TextField()),
                ('city_recommendation', models.TextField()),
            ],
            options={
                'unique_together': {('sun_sign', 'ascendant_sign')},
            },
        ),
    ]
