# Generated by Django 5.0.7 on 2024-07-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0010_askastroquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probabilitiescomments',
            name='monthly_comment',
        ),
    ]
