# Generated by Django 5.0.7 on 2024-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natalcharts', '0011_remove_probabilitiescomments_monthly_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='probabilitiescomments',
            name='monthly_comment',
            field=models.TextField(default='default'),
        ),
    ]
